pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "Running build ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh 'google-chrome --version'
        sh 'pwd'
        sh 'ls -l'
      }
    }
  }
}
